### ISSUE TITLE
'ColorSchemeSwitch' imported twice in petal_pro_web.ex

### ISSUE THREAD

**Issue by pauljmathews** [petalframework/petal_pro_issues#12]
**Describe the bug**
A minor thing, ColorSchemeSwitch is listed twice in petal_pro_web.ex (line 121)

**To Reproduce**
1. Go to '/lib/petal_pro_web.ex'
2. Read line 121
3. See duplicate import of 'ColorSchemeSwitch'
4. App compiles with no issues, but should only be listed once

**Expected behavior**
App compiles and runs, but would be best to remove the extra import

**Screenshot**
<img width="409" alt="Screen Shot 2022-03-20 at 12 06 55 PM" src="https://user-images.githubusercontent.com/2317389/159174069-ec07c963-bb34-4324-812d-a84d37a10846.png">

**Comment by mplatts** [comment]
Thanks! Fixed in the next version
