### ISSUE TITLE
Unit tests fail when using petal.gen.live

### ISSUE THREAD

**Issue by pauljmathews** [petalframework/petal_pro_issues#14]
**Describe the bug**
Generator works great and renders working code, but 6 unit tests are failing

**To Reproduce**
1. Create a clean new project from petal_pro_1.1.1
2. Run mix setup, etc... run mix test, all tests pass
3. Run -> `mix petal.gen.live Todos Todo todos label:string is_done:boolean`
4. Run `mix ecto.migrate`
5. Run `mix test`
6. Six unit tests fail 

```
** (MatchError) no match of right hand side value: {:error, {:redirect, %{flash: %{"error" => "You must log in to access this page."}, to: "/users/sign-in"}}}

test/petal_pro_web/live/todo_live_test.exs:19
test/petal_pro_web/live/todo_live_test.exs:26
test/petal_pro_web/live/todo_live_test.exs:48
test/petal_pro_web/live/todo_live_test.exs:70
test/petal_pro_web/live/todo_live_test.exs:81
test/petal_pro_web/live/todo_live_test.exs:88
```

**Expected behavior**
Tests should pass after running the generator

**Screenshots**
N/A

**Environment**
MacOS (M1 chip)
elixir -> 1.13.2
erlang -> 24.2.1
nodejs -> 14.18.0

**Comment by mplatts** [comment]
Should be fixed with https://github.com/petalframework/petal_pro/commit/ebd52ffb762aa96ac128d228b6c5a6813a08bac0

![CleanShot 2022-04-04 at 10 37 36](https://user-images.githubusercontent.com/184383/161456456-b6bb8c7c-acb8-4b5c-b829-f6cbc3b5c12f.png)

**Comment by pauljmathews** [comment]
Fixed - Thanks!
